### DISCUSSION TITLE
Hosting 2 Galleries on 1 RPI4B and face tagging

### DISCUSSION THREAD

**Discussion by GWONG3** [bpatrik/pigallery2#443] [Q&A] [answered]
Hi there,
I love pigallery2, fast and easy to setup!  Have everything I need!  

My setup - RPI4B, original images/tmp folders on NAS, using docker-compose.

1. how do I host 2 galleries on 1 host; e.g. 1 for myself and 1 for my kid?  Right now; i have 2 sets of compose-docker.yml files on 2 different folders on my RPI; i.e. 2 containers and so I access my galleries 192.168.1.10:1234, and 192.168.1.10:5678.  I am sure there should be a smarter way to do this; at least can use 1 docker-compose.yml and define 2 containers but I am not sure what the correct settings; e.g. can I use the same config and db-data for both or have to create seperately?

2. I want to tag people on my photos.  Any beginner for dummy 101 guides how to setup that up can share with me :)?

Thank you!
Regards,
GWONG3

**Comment by jimdaway** [comment]
Hi @GWONG3 
Did you figure this out as I am trying to do the same thing (actually, more than 2

**Comment by martadinata666** [comment, marked as answer]
Just copy repeat 
```
version: '3'
services:
  pigallery2:
    image: bpatrik/pigallery2:latest
    container_name: pigallery2
    environment:
      - NODE_ENV=production
    volumes:
      - "./pigallery2/config:/app/data/config" # CHANGE ME
      - "db-data:/app/data/db"
      - "./pigallery2/images:/app/data/images:ro" # CHANGE ME, ':ro' mean read-only
      - "./pigallery2/tmp:/app/data/tmp" # CHANGE ME
    ports:
      - 1234:80
    restart: always

  pigallery2son:
    image: bpatrik/pigallery2:latest
    container_name: pigallery2son
    environment:
      - NODE_ENV=production
    volumes:
      - "./pigallery2son/config:/app/data/config" # CHANGE ME
      - "db-data-son:/app/data/db"
      - "./pigallery2son/images:/app/data/images:ro" # CHANGE ME, ':ro' mean read-only
      - "./pigallery2son/tmp:/app/data/tmp" # CHANGE ME
    ports:
      - 1235:80
    restart: always

volumes:
  db-data:
  db-data-son:
```
Just check and be carefull, the directory not overlap each-other
