### DISCUSSION TITLE
Is it possible to read from an SMB share?

### DISCUSSION THREAD

**Discussion by PXAbstraction** [bpatrik/pigallery2#658] [Q&A]
Hey everyone! I'm considering using PiGallery 2 in order to make a gallery of my old live stream clips available to my community. Currently, all the clips are stored on an SMB share on another system as there are a large number of them. Is it possible to use an SMB share as the source for the gallery? If not directly, is there a workaround method to do this? Thanks so much!

**Comment by devLeitner** [comment]
Hey, I know it's not the answer you are looking for specifically, but I am using an NFS-Share to do a similar thing. I setup a NFS-Share with all of my pictures, created a docker-volume referencing the nfs-share and setting the volume as picture root. Works well in my case. Maybe it helps :D

**Comment by bencollinz** [comment]
Yes, you absolutely can. 


```
volumes:
  db-data:
    driver_opts:
      type: cifs
      o: "username=USER,password=PASSWORD,rw"
      device: "IP ADDRESS/share"
```


edit: I can't get the spacing to show up correctly, but you get the point
