### DISCUSSION TITLE
Please help a novice get set up (pigallery2 in Portainer, images in nextcloud)

### DISCUSSION THREAD

**Discussion by m90att** [bpatrik/pigallery2#754] [Q&A]
Hi,

I really like the look of pigallery2 and have spent 2 days trying to set it up.  I am a novice so am using Portainer on a raspberry pi 4B with a container for pigallery2 and a container for nextcloud, where the photos are located.  Using Portainer, I haven't needed to create a docker compose file or edit any other configuration.  I've got pigallery2 running but I cannot find out how to point it to nextcloud to actually see the photos.  There doesn't seem to be the support for novice users like myself available.  I've searched and read so much but it's all requiring editing things that I haven't needed to do as part of the install.  The instructions say that you can set it up using the settings in the UI which I've tried but the settings for host aren't intuitive so I'm purely guessing and not having any success.

Would anyone be kind enough to spare some time to help a beginner please?

Thanks in advance,

Matt

**Comment by bpatrik** [comment]
I'm not deeply familiar with nextcloud, but to my understand that is not possible out of the box. nextcloud uses its own file system/way of storing files that are not available outside nextcloud. There is some extension to export files somehow. 

I rather use this setup:
portainer, nginx proxy manager + pigallery2, filestash

**Comment by rhatguy** [comment]
you can definitely do this.  I do the same thing running on Unraid.  Nextcloud stores the photos in a particular directory, but as long as you mount that same directory into the PiGallery2 container it will happily read the files from the same place.  In my case I have a folder on the host system mounted into the Nextcloud data directory, and that same folder also mounted into PiGallery2 (In read-only so there is never any danger of PiGallery2 changing any of my photos).  I think we can give you pointers and confirm that what you're doing is possible, but you're probably going to need to do some digging/learning to understand how docker bind mountpoints work.  The idea is to mount the same folder from the host OS into the Nextcloud container as the data mountpoint and into the PiGallery2 container as its data mountpoint.

This for example shows how my data directory is mounted into Nextcloud
           {
                "Type": "bind",
                "Source": "**/mnt/user/nextcloud/data**",
                "Destination": "/var/www/html/data",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }

Then PiGallery2s container gets the same host folder (a little deeper into the path) mounted into it
            {
                "Type": "bind",
                "Source": "**/mnt/user/nextcloud/data**/pictures/files/mylio_vault",
                "Destination": "/app/data/images",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },

**Comment by martadinata666** [comment]
Use nextcloud external storage function

**Comment by bpatrik** [comment]
After @rhatguy's comment I gave next could an other try. I set my data dir to my /mnt/nextcloud folder (I would be able to mount that to pigallery). But I rather user external storage to mount only one pigallery folder to nextcloud.

Here are my portainer stacks:

```
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'WATCHTOWER_DOCKER_SOCKET_PATH'!
    ports:
    #  - 80:80 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - 8080:8080
    #  - 8443:8443 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
    environment: # Is needed when using any of the options below
      # - AIO_DISABLE_BACKUP_SECTION=false # Setting this to true allows to hide the backup section in the AIO interface. See https://github.com/nextcloud/all-in-one#how-to-disable-the-backup-section
      - APACHE_PORT=11000 # Is needed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - APACHE_IP_BINDING=127.0.0.1 # Should be set when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else) that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      # - BORG_RETENTION_POLICY=--keep-within=7d --keep-weekly=4 --keep-monthly=6 # Allows to adjust borgs retention policy. See https://github.com/nextcloud/all-in-one#how-to-adjust-borgs-retention-policy
      # - COLLABORA_SECCOMP_DISABLED=false # Setting this to true allows to disable Collabora's Seccomp feature. See https://github.com/nextcloud/all-in-one#how-to-disable-collaboras-seccomp-feature
      - NEXTCLOUD_DATADIR=/mnt/nextcould # Allows to set the host directory for Nextcloud's datadir. ⚠️⚠️⚠️ Warning: do not set or adjust this value after the initial Nextcloud installation is done! See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
      - NEXTCLOUD_MOUNT=/mnt/images/somepigallery2folder # Allows the Nextcloud container to access the chosen directory on the host. See https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host
      # - NEXTCLOUD_UPLOAD_LIMIT=10G # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-upload-limit-for-nextcloud
      # - NEXTCLOUD_MAX_TIME=3600 # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-max-execution-time-for-nextcloud
      # - NEXTCLOUD_MEMORY_LIMIT=512M # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-php-memory-limit-for-nextcloud
      # - NEXTCLOUD_TRUSTED_CACERTS_DIR=/path/to/my/cacerts # CA certificates in this directory will be trusted by the OS of the nexcloud container (Useful e.g. for LDAPS) See See https://github.com/nextcloud/all-in-one#how-to-trust-user-defined-certification-authorities-ca
      # - NEXTCLOUD_STARTUP_APPS=deck twofactor_totp tasks calendar contacts notes # Allows to modify the Nextcloud apps that are installed on starting AIO the first time. See https://github.com/nextcloud/all-in-one#how-to-change-the-nextcloud-apps-that-are-installed-on-the-first-startup
      # - NEXTCLOUD_ADDITIONAL_APKS=imagemagick # This allows to add additional packages to the Nextcloud container permanently. Default is imagemagick but can be overwritten by modifying this value. See https://github.com/nextcloud/all-in-one#how-to-add-os-packages-permanently-to-the-nextcloud-container
      # - NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS=imagick # This allows to add additional php extensions to the Nextcloud container permanently. Default is imagick but can be overwritten by modifying this value. See https://github.com/nextcloud/all-in-one#how-to-add-php-extensions-permanently-to-the-nextcloud-container
      # - NEXTCLOUD_ENABLE_DRI_DEVICE=true # This allows to enable the /dev/dri device in the Nextcloud container. ⚠️⚠️⚠️ Warning: this only works if the '/dev/dri' device is present on the host! If it should not exist on your host, don't set this to true as otherwise the Nextcloud container will fail to start! See https://github.com/nextcloud/all-in-one#how-to-enable-hardware-transcoding-for-nextcloud
      # - NEXTCLOUD_KEEP_DISABLED_APPS=false # Setting this to true will keep Nextcloud apps that are disabled in the AIO interface and not uninstall them if they should be installed. See https://github.com/nextcloud/all-in-one#how-to-keep-disabled-apps
      # - TALK_PORT=3478 # This allows to adjust the port that the talk container is using. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-talk-port
      # - WATCHTOWER_DOCKER_SOCKET_PATH=/var/run/docker.sock # Needs to be specified if the docker socket on the host is not located in the default '/var/run/docker.sock'. Otherwise mastercontainer updates will fail. For macos it needs to be '/var/run/docker.sock'
      - SKIP_DOMAIN_VALIDATION=true
    # networks: # Is needed when you want to create the nextcloud-aio network with ipv6-support using this file, see the network config at the bottom of the file
      # - nextcloud-aio # Is needed when you want to create the nextcloud-aio network with ipv6-support using this file, see the network config at the bottom of the file
    # # Uncomment the following line when using SELinux
    # security_opt: ["label:disable"]

  # # Optional: Caddy reverse proxy. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
  # # You can find further examples here: https://github.com/nextcloud/all-in-one/discussions/588
  # caddy:
  #   image: caddy:alpine
  #   restart: always
  #   container_name: caddy
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     - ./certs:/certs
  #     - ./config:/config
  #     - ./data:/data
  #     - ./sites:/srv
  #   network_mode: "host"

volumes: # If you want to store the data on a different drive, see https://github.com/nextcloud/all-in-one#how-to-store-the-filesinstallation-on-a-separate-drive
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not work

# # Optional: If you need ipv6, follow step 1 and 2 of https://github.com/nextcloud/all-in-one/blob/main/docker-ipv6-support.md first and then uncomment the below config in order to activate ipv6 for the internal nextcloud-aio network.
# # Please make sure to uncomment also the networking lines of the mastercontainer above in order to actually create the network with docker-compose
# networks:
#   nextcloud-aio:
#     name: nextcloud-aio # This line is not allowed to be changed as otherwise the created network will not be used by the other containers of AIO
#     driver: bridge
#     enable_ipv6: true
#     ipam:
#       driver: default
#       config:
#         - subnet: fd12:3456:789a:2::/64 # IPv6 subnet to use
```
pigallery stack: (replace the reducted text to something like `/home/john/`):
```
version: '3'
services:
  pigallery2:
    image: bpatrik/pigallery2:edge-debian-bullseye
    container_name: pigallery2
    environment:
      - NODE_ENV=production
#       - NODE_ENV=debug
    volumes:
      - "<reducted>configs/pigallery2/config:/app/data/config" # CHANGE ME
      - "db-data:/app/data/db"
      - "/mnt/images:/app/data/images:ro" # CHANGE ME, ':ro' mean read-only
      - "/mnt/pigallery2-tmp:/app/data/tmp" # CHANGE ME
    expose:
      - "80"
    restart: always
    networks:
     - frontend

volumes:
  db-data:

networks:
  frontend:
    name: frontend
    external: true
```
nginx-proxy-managerstack: (replace the reducted text):
```
version: '3.8'
services:
  app:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    # network_mode: host
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - <reducted>configs/nginx-proxy-manager/data:/data
      - <reducted>configs/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - frontend

networks:
  frontend:
    name: frontend

```

I use nginx-proxy-manager in front of pigallery and nextcloud. I made sure that are on the same network then:

![kép](https://github.com/bpatrik/pigallery2/assets/7512182/adea1305-3e81-467a-84a3-c64a2429db67)
On the advanced tab:
```
gzip on;
	gzip_proxied any;
	gzip_comp_level 6;
	gzip_types
		text/css
		text/plain
		text/javascript
		text/markdown
		application/javascript
		application/json
		application/gpx+xml
		application/x-javascript
		application/xml
		application/xml+rss
		application/xhtml+xml
		application/x-font-ttf
		application/x-font-opentype
		application/vnd.ms-fontobject
		image/svg+xml
		image/x-icon
		application/rss+xml
		application/atom_xml;
  gzip_disable "MSIE [1-6]\.(?!.*SV1)";

    # Only allow all methods (GET,POST,PUT,etc..) for root (/pgapi).
    # see https://github.com/bpatrik/pigallery2/issues/214
    location /pgapi {
      proxy_pass http://pigallery2:80; # forwarding to the other container, named 'pigallery2'
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }

    location / {
      limit_except GET {
        deny  all;
      }
      proxy_pass http://pigallery2:80; # forwarding to the other container, named 'pigallery2'
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }
```

For nextcould I followed this: https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
And set up this in NPM:
![kép](https://github.com/bpatrik/pigallery2/assets/7512182/59821ee3-cf8d-4083-bbb5-eef5f77f2460)
