### DISCUSSION TITLE
Cert autorenew

### DISCUSSION THREAD

**Discussion by MadParkerD** [bpatrik/pigallery2#968] [General]
Took me a little while to work out what the easiest way to autorenew the cert in the default config here was (nginx in container, certbot outside). Leaving it here for reference for folks who don't know much about websites and want to copy paste

```
#docker compose snippet
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/
      # If desired mount a location to use for letsencrypt autorenew using the webroot plugin e.g.
      # - type: bind                      #allow certbot to write into the docker container without restarting anything
      #   source:  /usr/share/nginx/html/ #default webroot location on ubuntu, this can be anywhere that is mountable and docker will have perms to access
      #   target: /etc/nginx/html         #default webroot inside the nginx:latest container at time of commit, needs to match to a root in an nginx.conf location block
      # # # # Example certbot command to set up autorenew, webroot path needs to match the source of the bind above: 
      # # # # # certbot certonly --webroot --webroot-path /usr/share/nginx/html -d <YOUR_DOMAIN_HERE>
```

```
#nginx.conf snippet
    # Optional location block for use by certbot's webroot acme-challenge
    # This should probably go in your proxy server block
    location /.well-known {
      allow all;            # Technically this probably only needs a get
      root /etc/nginx/html; # Needs to match a location mounted via the docker compose file as a bind
     }
```
