### ISSUE TITLE
Incorrect aspect ratio for thumbnail/preview

### ISSUE THREAD

**Issue by cbhushan** [bpatrik/pigallery2#212]
**Describe the bug**
Thumbnail/preview has incorrect aspect ratio for one of my images, as shown in screenshot below. The image is also linked below. 

**Photo/video (optional) that causes the bug**
See zip: https://www.dropbox.com/s/ee7vw513vl79nuv/testimg.tar.gz?dl=0 

**Screenshots**
Left thumbnail has correct aspect ratio. Right one (__a20180218_143832_dc8f44e06e4a.jpg) is incorrect. Both images are attached in link above.
![image](https://user-images.githubusercontent.com/3436053/103162601-9be98f00-47c0-11eb-9559-2193fb9d21f9.png)

**Environment (please complete the following information):**
 - Browser: Firefox 84.0 (64-bit)
 - OS: Ubuntu 20.04.1
 
**Used app version**:
- docker-nightly. See screenshot below for version.
![image](https://user-images.githubusercontent.com/3436053/103162679-832da900-47c1-11eb-93c2-54f88f2d5fca.png)

docker-compose.yml:
```
version: '3'
services:
  pigallery-db:
    container_name: pigallery-db
    image: mariadb
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=putsomethinginherethatyouwouldlikeasthepassword
      - MYSQL_USER=pigallery2
      - MYSQL_PASSWORD=pigallery2_pass
      - MYSQL_DATABASE=pigallery2

  pigallery2:
    image: bpatrik/pigallery2:nightly-stretch
    command: sh -c 'bin/wait-for pigallery-db:3306 -- --Server-Database-mysql-host=pigallery-db --Server-Database-mysql-username=pigallery2 --Server-Database-mysql-password=pigallery2_pass --Server-Database-mysql-database=pigallery2'
    container_name: pigallery2
    environment:
      - NODE_ENV=production
    volumes:
      - "/mnt/data/tmp/PiGallery2/config:/app/data/config" # CHANGE ME
      - "db-data:/app/data/db"
      - "/mnt/data/tmp/pic_collection:/app/data/images/pic_collection" # CHANGE ME
      - "/mnt/data/tmp/pic_collection2:/app/data/images/pic_collection2" # CHANGE ME
      - "/mnt/data/tmp/PiGallery2/tmp:/app/data/tmp" # CHANGE ME
    ports:
      - 80:80
    restart: always

volumes:
  db-data:

```
