### ISSUE TITLE
Two pigalleries on one server

### ISSUE THREAD

**Issue by h0n2a** [bpatrik/pigallery2#258]
Is possible to run two pigalleries on one physical server?

I want to share two categories of photos with two different groups of people.
Since pigallery can't mange access rights for different accounts, the idea is to run two instances of pigallery for each category of photos. Each instance should be accessible from different domain.

I think it should be possible with reverse proxy, but my knowledge is limited here and I would appreciate some help with the setup.

I have now running pigallery with docker-compose.
Thanks

**Comment by bpatrik** [comment]
Yes it should be possible. 
Reverse proxy is not needed at all, just helps with https, and gives some extra protection to the app.

You will need to run the 2. gallery on a different port (def is 80 for http, 443 for https). Also make sure that you use have a separate config and db for the 2. one (you can set those up in the docer-compose file).

If you want to use reverse proxy (like nginx) you also need to change that config too. 


A solution idea (without testing) can be e.g.:
Add a new pigallery container to your compose file:
https://github.com/bpatrik/pigallery2/blob/f76db930b8058636cc5cb579272dc778690150cb/docker/docker-compose/default/docker-compose.yml#L16-L28
Probably you should change all values below the `volumes` tag. The port can stay at 80, just make sure you change the container name.

And add a new `location` or `server` to the nginx.config file(not sure witch one, never tried to do this before): https://github.com/bpatrik/pigallery2/blob/f76db930b8058636cc5cb579272dc778690150cb/docker/docker-compose/default/nginx.conf#L59-L66
That should use something like `location /<name of the 2nd gallery>`, proxy path should point to the newly created container and set up the `base url` in the app's config for the 2nd gallery.

**Comment by Magneticdud** [comment]
Totally possible. I run two galleries on same server. I use docker.

I created two docker-compose.yml files, but on different ports.

Then I'm using nginx as a reverse proxy, so they both can run on port 80. If you need examples, I can paste here

**Comment by h0n2a** [comment]
> If you need examples, I can paste here

Yes, please, I would appreciate that. I have very limited time to experiment, so example of a working solution would be great.

**Comment by Magneticdud** [comment]
### docker:

directory1:

/docker/pigallery2-1/docker-compose.yml:

```
version: '3'
services:
  pigallery2:
    image: bpatrik/pigallery2:latest
    container_name: pigallery2
    environment:
      - NODE_ENV=production
    volumes:
      - "./config:/app/data/config"
      - "./db-data:/app/data/db"
      - "/photos/:/app/data/images:ro"
      - "./tmp:/app/data/tmp"
    ports:
      - 8001:80
    restart: unless-stopped
```

directory2:

/docker/pigallery2-alternate/docker-compose.yml:

```
version: '3'
services:
  pigallery2:
    image: bpatrik/pigallery2:latest
    container_name: pigallery2
    environment:
      - NODE_ENV=production
    volumes:
      - "./config:/app/data/config"
      - "./db-data:/app/data/db"
      - "/other-photos/:/app/data/images:ro"
      - "./tmp:/app/data/tmp"
    ports:
      - 8002:80
    restart: unless-stopped
```

### nginx:

for first gallery:

/etc/nginx/sites-enabled/your.example.com

```
server {
        server_name your.example.com;
        location / {
                proxy_pass http://192.168.1.1:8001;
                proxy_set_header  X-Real-IP  $remote_addr;
                proxy_set_header X-Forwarded-For $remote_addr;
                proxy_set_header Host $host;
        }
    listen 80;
}
```

for second gallery:

/etc/nginx/sites-enabled/other-gallery.example.com

```
server {
        server_name other-gallery.example.com;
        location / {
                proxy_pass http://192.168.1.1:8002;
                proxy_set_header  X-Real-IP  $remote_addr;
                proxy_set_header X-Forwarded-For $remote_addr;
                proxy_set_header Host $host;
        }
    listen 80;
}
```

nginx config could be in the same file but separate is more convenient. Also the right way is placing the conf files in sites-available then symlinking them in sites-enabled. A script like [nginx_modsite](https://www.ajsalkeld.com/blog/project/2016/07/16/Nginx-modsite-a2ensite-tool-for-nginx-enable-disable-reload/) can speed up the process
