### ISSUE TITLE
Database (shares, albums, etc.) are lost on upgrade

### ISSUE THREAD

**Issue by SlavikCA** [bpatrik/pigallery2#317]
**Describe the bug**
I'm running piGallery2 via Docker.
DB mounted to the host:
```
version: '3'
services:
  pigallery2:
    image: bpatrik/pigallery2:nightly-alpine
    volumes:
      - /volume1/hosting/piGallery2/config:/app/data/config
      - /volume1/hosting/piGallery2/db-data:/app/data/db
      - /volume1/pix/Photos_Personal:/app/data/images:ro
      - /volume1/hosting/piGallery2/cache:/app/data/tmp
    environment:
      NODE_ENV: production
```

Every time I pull new version of the image and restart the container - all my shares are lost.

I can't point to exact builds 
Now I'm on commit f2ab96faaf0593319912fb0da737b6d50f45ac67.
I'll recreate few shares now and we'll try later with another version in a few days again.

Can the issue be because I'm using nightly builds? Will shares be preserved if I use LATEST tag for Docker image instead?
