### ISSUE TITLE
MariaDB emojis in folder name

### ISSUE THREAD

**Issue by TheFirstMonster** [bpatrik/pigallery2#399]
**Describe the bug**

When indexing a folder that has an emoji in its name PiGallery throws following error:
```
QueryFailedError: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x99\x82' for column `pigallery2`.`directory_entity`.`name` at row 1
    at new QueryFailedError (/app/node_modules/typeorm/error/QueryFailedError.js:12:28)
    at Query.<anonymous> (/app/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:217:45)
    at Query.<anonymous> (/app/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/app/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/app/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  code: 'ER_TRUNCATED_WRONG_VALUE_FOR_FIELD',
  errno: 1366,
  sqlMessage: "Incorrect string value: '\\xF0\\x9F\\x99\\x82' for column `pigallery2`.`directory_entity`.`name` at row 1",
  sqlState: '22007',
  index: 0,
  sql: "INSERT INTO `directory_entity`(`id`, `name`, `path`, `lastModified`, `lastScanned`, `mediaCount`, `parentId`) VALUES (DEFAULT, '🙂', './', 1639761429229, 1639761455199, 0, DEFAULT)",
  query: 'INSERT INTO `directory_entity`(`id`, `name`, `path`, `lastModified`, `lastScanned`, `mediaCount`, `parentId`) VALUES (DEFAULT, ?, ?, ?, ?, ?, DEFAULT)',
  parameters: [ '🙂', './', 1639761429229, 1639761455199, 0 ]
}
```

`docker-compose.yml`
```
version: '3'
services:
  pigallery2:
    image: bpatrik/pigallery2:nightly-debian-buster
    container_name: pigallery2
    environment:
      - NODE_ENV=production
    volumes:
      - "./config:/app/data/config"
      - "db-data:/app/data/db"
      - "./images:/app/data/images:ro"
      - "./tmp:/app/data/tmp"
    ports:
      - 8040:80
    restart: always
   
  pigallery-db:
    container_name: pigallery-db
    image: mariadb
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=pigallery2
      - MYSQL_PASSWORD=pigallery2
      - MYSQL_DATABASE=pigallery2
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  db-data:
```

I think the problem is that the db client is using `utf8/utf8mb3` as charset instead of `utf8mb4` which supports emojis.
Also the database should be initialized with `utf8mb4`.
