### ISSUE TITLE
Error on thumbnail generation after indexing files

### ISSUE THREAD

**Issue by AlvMG** [bpatrik/pigallery2#434]
**Describe the bug**

It seems that there is an issue on the generation of the thumbnail after indexing files when we have a big amount of files. On the UI is showing this:
#0 [24 feb. 2022 9:57:54] Loading files from db 
![imagen](https://user-images.githubusercontent.com/17013630/155531584-9625f678-024e-4349-a682-a3069c27df7c.png)

And on the docker logs we can see this:
```
2/24/2022, 8:57:54 AM[INFO_][JOB] Running job : Thumbnail Generation

2/24/2022, 9:00:27 AM[ERROR][JOB] RangeError: Maximum call stack size exceeded

    at ThumbnailGenerationJob.<anonymous> (/app/src/backend/model/jobs/jobs/FileJob.js:138:28)

    at Generator.next (<anonymous>)
```

I am using the latest version at the moment

**Comment by AlvMG** [comment]
Hi,
yeah I am using the nightly version:
![imagen](https://user-images.githubusercontent.com/17013630/155836096-232cb1c7-0dc1-45c0-9acf-893f24f82009.png)
I have more files than you I think:
![imagen](https://user-images.githubusercontent.com/17013630/155836147-78aad6f1-18b0-4266-bcc4-f10714764046.png)

**Comment by desertwitch** [comment]
Your screenshot shows you are using the outdated **latest** tag and not the **nightly** tag, where this issue is fixed.

**Comment by AlvMG** [comment]
Cool thanks! I will update the version!

**Comment by AlvMG** [comment]
Hi,
I tried to move to the nightly version, but is not starting. I have this logs constanly:
`3/1/2022, 8:51:18 AM[INFO_][server] running diagnostics...`
And with the debug mode ther is no more logs only this:
```
[Typeconfig] Processing cli and ENV inputs: {

	"PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",

	"HOSTNAME": "601e1d6d1171",

	"NODE_ENV": "debug",

	"NODE_VERSION": "14.19.0",

	"YARN_VERSION": "1.22.17",

	"PI_DOCKER": true,

	"HOME": "/root"

```
my docker compose is the following, just in case I am doing something wrong (is working fine with the latest version):

```
version: '3'
services:
  pigallery-db:
    container_name: pigallery-db
    image: mariadb
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=XXXXXX
      - MYSQL_USER=XX
      - MYSQL_PASSWORD=XXX
      - MYSQL_DATABASE=X

  pigallery2:
    image: bpatrik/pigallery2:latest-debian-buster
    command: sh -c 'bin/wait-for pigallery-db:3306 -- --Server-Database-mysql-host=pigallery-db --Server-Database-mysql-username=XX --Server-Database-mysql-password=XXX --Server-Database-mysql-database=X'
    container_name: pigallery2
    environment:
      - NODE_ENV=production
    volumes:
      - "/srv/8079f001-5556-4ae8-9e4a-0c2453d888bc/config/pigallery2/config:/app/data/config" # CHANGE ME
      - "db-data:/app/data/db"
      - "/srv/8079f001-5556-4ae8-9e4a-0c2453d888bc/movil:/app/data/images/movil:ro" # CHANGE ME, ':ro' mean read-only
      - "/srv/8079f001-5556-4ae8-9e4a-0c2453d888bc/fotos:/app/data/images/fotos:ro" # CHANGE ME, ':ro' mean read-only
      - "/srv/8079f001-5556-4ae8-9e4a-0c2453d888bc/config/pigallery2/tmp:/app/data/tmp" # CHANGE ME
    ports:
      - 85:80
    restart: always

volumes:
  db-data:
```
maybe there is another way to connect the db with the gallery.
Thanks!
