### ISSUE TITLE
docker-compose file

### ISSUE THREAD

**Issue by palitu** [bpatrik/pigallery2#46]
Here is a quick docker-compose file which will pull the latest stable pigallery2 and mariadb to allow you to quickly transistion from sqlite to mysql.

this will create the pigallery table in mariadb, which you can then connect to.  

**Note i had to put in the docker IP address into the MySQL configuration**

just make sure you update your volume paths and passwords.  

```
pigallery-db:
   container_name: pigallery-db
   image: mariadb
   # links:
   #    - pigallery:pigallery-db
   volumes:
      - /storage/pigallery/data/db:/var/lib/mysql
   environment:
     - MYSQL_ROOT_PASSWORD=putsomethinginherethatyouwouldlikeasthepassword
     - MYSQL_USER=pigallery 
     - MYSQL_PASSWORD=pigallery
     - MYSQL_DATABASE=pigallery


pigallery:
   container_name: pigallery
   image: bpatrik/pigallery2:nightly-stretch
   volumes:
      - /storage/pigallery/data/config.json:/pigallery2-release/config.json
      - /storage/pigallery/data/sqlite.db:/pigallery2-release/sqlite.db
      - /storage/pigallery/photos:/pigallery2-release/demo/images
      - /storage/pigallery/data/temp:/pigallery2-release/demo/TEMP
   environment:
      - NODE_ENV=production
   ports:
      - "1112:80"


```

@bpatrik, perhaps you could add this to the installation instructions.

cheers,
