### ISSUE TITLE
Specific face cannot be filtered on

### ISSUE THREAD

**Issue by b-a0** [bpatrik/pigallery2#564]
**Describe the bug**

I have an instance with 14k photos and about 160 folders. All works well, but one particular face (with about 700 photos) cannot be filtered on. For example's sake I'll name the face Lily Olaly.

- If I go to Faces in the menu and click on the thumbnail of the face Lily Olaly, the page changes, but the loading icon (a rotating square) keeps showing and nothing changes.
- If I open a photo with the face of Lily Olaly (this works fine) and click on the face overlay of Lily Olaly, the same happens as above.
- If I search for the face in the searchbar with `person:"Lily Olaly"` the same happens as above.

**Photo/video (optional) that causes the bug**

N/A

**Screenshots (optional)**

N/A

**Server logs (optional)**

In case of a server side error, provide logs:

```log
pigallery2  | [Typeconfig] Processing cli and ENV inputs: {
pigallery2  |   "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
pigallery2  |   "HOSTNAME": "4233a1f46dab",
pigallery2  |   "NODE_ENV": "debug",
pigallery2  |   "NODE_VERSION": "14.19.0",
pigallery2  |   "YARN_VERSION": "1.22.17",
pigallery2  |   "PI_DOCKER": true,
pigallery2  |   "HOME": "/var/www",
pigallery2  |   "VIPS_MIN_STACK_SIZE": "2m",
pigallery2  |   "VIPSHOME": "/target"
pigallery2  | }
pigallery2  | NODE_ENV environmental variable is set to debug, forcing all logs to print
pigallery2  | 12/3/2022, 12:39:16 PM[DEBUG][Worker] Worker is waiting for tasks
pigallery2  | 12/3/2022, 12:39:29 PM[DEBUG][PersonManager] Updating derived persons data
pigallery2  | 12/3/2022, 12:39:30 PM[VERBS] GET /api/person 304 622ms
...
pigallery2  | 12/3/2022, 12:39:30 PM[VERBS] GET / 304 20ms
pigallery2  | 12/3/2022, 12:39:48 PM[WARN_] Handled error:
pigallery2  | ErrorDTO {
pigallery2  |   code: 7,
pigallery2  |   message: 'Error during searching',
pigallery2  |   details: SyntaxError: Unexpected token D in JSON at position 197
pigallery2  |       at JSON.parse (<anonymous>)
pigallery2  |       at SearchManager.<anonymous> (/app/src/backend/model/database/sql/SearchManager.js:166:69)
pigallery2  |       at Generator.next (<anonymous>)
pigallery2  |       at fulfilled (/app/src/backend/model/database/sql/SearchManager.js:5:58)
pigallery2  |       at processTicksAndRejections (internal/process/task_queues.js:95:5),
pigallery2  |   request: { method: '', url: '' },
pigallery2  |   detailsStr: 'SyntaxError: Unexpected token D in JSON at position 197'
pigallery2  | }
pigallery2  | 12/3/2022, 12:39:48 PM[VERBS] GET / 304 395ms
pigallery2  | 12/3/2022, 12:39:50 PM[DEBUG] HEAD /heartbeat 200 6ms
```

**Environment (please complete the following information):**
 - OS: Raspbian Buster
```
> lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```
```
> uname -a
Linux rpi4 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux
```
 - Browser: Firefox 107.0.1 (64-bit), but also tried on Safari 16.1 (17614.2.9.1.13, 17614), both on macOS Monterey 12.6.1

**Used app version**:
- `bpatrik/pigallery2:latest` pushed to docker hub on Mar 12, 2022 at 9:32 pm.

Used docker compose file:

```yaml
version: '3'
services:
  pigallery2:
    user: '33:33'  # To be able to read the data stored by Nextcloud which runs as www-data (id=33)
    image: bpatrik/pigallery2:latest
    container_name: pigallery2
    environment:
      - NODE_ENV=debug
    volumes:
      - "./config:/app/data/config"
      - "./db-data:/app/data/db"
      - "/media/ssd/nextcloud/data/ba/files/Photos:/app/data/images:ro"
      - "./tmp:/app/data/tmp"
    ports:
      - 8081:80
    restart: always
```
