### ISSUE TITLE
traefik uncompability ?

### ISSUE THREAD

**Issue by SaigneurreungiaS** [bpatrik/pigallery2#943]
Hello,

I use docker version of pigallery2.

On LAN it works fine but when I try to use it behind Traefik I can access to the gallery.
I use it like all the other services behind Traefik.

The only difference between the two usages is ports and labels.

Here is what works : 
_

> version: '3.9'
> services:
>   pigallery2:
>     image: bpatrik/pigallery2:latest
>     container_name: pigallery2
>     environment:
>       - NODE_ENV=debug # set to 'debug' for full debug logging or stay on 'production'
>       # - NODE_OPTIONS=--enable-source-maps # enable source map support on the backend  for development
>     volumes:
>       - "/srv/docker/volumes/pigallery/config:/app/data/config" # CHANGE ME
>       - "/srv/docker/volumes/pigallery/db-data:/app/data/db"
>       - "/media/Images:/app/data/images:ro" # CHANGE ME, ':ro' means read-only
>       - "/srv/docker/volumes/pigallery/tmp:/app/data/tmp" # CHANGE ME
>     ports:
>       - 88:80
>     restart: always

_

and here is what doesn't : 

> _version: '3.9'
> services:
>   pigallery2:
>     image: bpatrik/pigallery2:latest
>     container_name: pigallery2
>     environment:
>       - NODE_ENV=debug # set to 'debug' for full debug logging or stay on 'production'
>       # - NODE_OPTIONS=--enable-source-maps # enable source map support on the backend  for development
>     volumes:
>       - "/srv/docker/volumes/pigallery/config:/app/data/config" # CHANGE ME
>       - "/srv/docker/volumes/pigallery/db-data:/app/data/db"
>       - "/media/Images:/app/data/images:ro" # CHANGE ME, ':ro' means read-only
>       - "/srv/docker/volumes/pigallery/tmp:/app/data/tmp" # CHANGE ME
>     #ports:
>      # - 88:80
>     restart: always
>     labels:
>       - "traefik.enable=true"
>       - "traefik.http.routers.photo.rule=Host(`photo.xyz.xyz`)"
>       - "traefik.http.routers.photo.entrypoints=web_secure"
>       - "traefik.http.routers.photo.tls=true"
>       - "traefik.http.routers.photo.tls.certresolver=certbot"
>       - "traefik.http.services.photo.loadbalancer.server.port=80"_

My host is RPI4 4Go,
OS : bookworm
docker : 5:27.3.1-1~debian.12~bookworm
docker-compose-plugin : 2.29.7-1~debian.12~bookworm
Traefik : 3.1.4 latest (docker image  sha256:3ae74a56d4d4d6b4c02ceef236a63c5f815f668a591d829ab75aa622cba3bdfc )
Pigallery2 : latest (docker image  sha256:4cabd81c689ad2f98c77a2fea138d999a31f0d86198b7f6e18d2348df07651a6 )

Client used for the tests : 
OS : debian
browser : Firefox 128.3.1esr (64 bits)

What can be the reason for this issue ?

**Comment by hsanson** [comment]
Maybe not much help but I can tell pigallery2 works fine behind traefik using docker installation. Here is my config that is working fine on my Debian Bookworm server:

```yaml
version: '2.2'
services:
  traefik:
    # https://hub.docker.com/_/traefik
    image: traefik:3.1.3
    container_name: traefik
    restart: unless-stopped
    mem_limit: 500M
    mem_swappiness: 5
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl:/ssl
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      # - --log.level=DEBUG
      - --api.insecure=true
      # See https://doc.traefik.io/traefik/observability/access-logs/
      - --accesslog
      # See https://doc.traefik.io/traefik/routing/entrypoints/#redirection
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      # See https://doc.traefik.io/traefik/https/acme/
      - --certificatesresolvers.godaddy.acme.tlschallenge=true
      - --certificatesResolvers.godaddy.acme.dnsChallenge.provider=godaddy
      - --certificatesResolvers.godaddy.acme.dnsChallenge.delayBeforeCheck=0
      - --certificatesresolvers.godaddy.acme.email=mail@email.com
      - --certificatesresolvers.godaddy.acme.storage=/ssl/godaddy.json
      # https://doc.traefik.io/traefik/providers/docker/
      - --providers.docker
      - --providers.docker.exposedByDefault=false
    labels:
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=goddady"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=domain.com"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.domain.com"
      - "traefik.http.routers.traefik-secure.service=api@internal"
    networks:
      - my-net

  pigallery2:
    image: bpatrik/pigallery2:edge-alpine
    container_name: pigallery2
    mem_limit: 4G
    mem_swappiness: 5
    environment:
      - NODE_ENV=production # set to 'debug' for full debug logging
      # - NODE_OPTIONS=--enable-source-maps # enable source map support on the backend for development
    ports:
      - "127.0.0.1:8083:80"
    labels:
      - "traefik.port=8083"
      - "traefik.enable=true"
      - "traefik.http.routers.pigallery2.rule=Host(`fotos.domain.com`)"
      - "traefik.http.routers.pigallery2.entrypoints=websecure"
      - "traefik.http.routers.pigallery2.tls.certresolver=godaddy"
    volumes:
      - ./pigallery2/config:/app/data/config
      - ./pigallery2/db:/app/data/db
      - ./pigallery2/originals:/app/data/images:ro
      - ./pigallery2/tmp:/app/data/tmp
    depends_on:
      - traefik
    networks:
      - my-net

networks:
  my-net:
```
