### ISSUE TITLE
documentation help

### ISSUE THREAD

**Issue by tropas2001** [bpatrik/pigallery2#964]
Please could documentation be provided for how to use the Users-enforcedUser config setting? I'm trying to use it in a docker file as an env variable and it's really not clear what the format should be?

**Comment by tropas2001** [comment]
Just to add - my best guess is 
`Users-enforcedUsers=["{\"role\":\"User\",\"name\":\"johndoe\",\"password\":\"pass1267675\"}"]`

**Comment by skatsubo** [comment]
Looks like you almost succeeded with guessing it. Based on your example I moved `[]` inside the quotes:

```yaml
services:
  pigallery2:
    environment:
      Users-enforcedUsers: '[{"role":"User","name":"johndoe","password":"pass123456"}]'
      NODE_ENV: debug
```
Log (cropped):
```
[Typeconfig] Processing cli and ENV inputs: {
	"Users": {
		"enforcedUsers": "[{\"role\":\"User\",\"name\":\"johndoe\",\"password\":\"pass123456\"}]"
	},

3/18/2025, 1:23:46 PM[VERBS][server] {
  "Users": {
    "enforcedUsers": [
      {
        "name": "johndoe",
        "role": 3,
        "password": "",
        "encryptedPassword": "$2b$09$T7ogDgu/xF.lXXY0Fzfy9ezZWEIrMmCbpG1w7S3qsmGFxMrb2yi3y",
        "encrypted": true
      }
    ]
  },
```
