### ISSUE TITLE
Rockchip FFMPEG HW Accelerated Transcoding

### ISSUE THREAD

**Issue by ioncubekh** [bpatrik/pigallery2#977]
**Is your feature request related to a problem? Please describe.**
Problem is faced on machines pigallery2 is made for that is SBCs like raspberry pi, orange pi, radxa...
Without HW-acceleration CPU just bogs down potentially degrading other docker containers

**Describe the solution you'd like**
Solution is pretty straightforward & for some time now utilised by Jellyfin. It is also referred here (although not for Rockchip https://github.com/bpatrik/pigallery2/issues/592)

Filters available in rockcip `scale_rkrga` & `vpp_rkrga`
Encoders `h264_rkmpp` & `hevc_rkmpp`

> https://jellyfin.org/docs/general/administration/hardware-acceleration/rockchip/

> https://github.com/hbiyik/ffmpeg-rockchip/wiki/Filter 

> https://github.com/hbiyik/ffmpeg-rockchip/wiki/Encoder

Full syntax that works in rockchip host for HW-accelerated encode `ffmpeg -hwaccel rkmpp -hwaccel_output_format drm_prime  -i MOV00132.wmv  -crf 23 -c:v h264_rkmpp -c:a aac -ab 80k MOV00132.mp4`

> https://github.com/hbiyik/ffmpeg-rockchip/wiki/Video-Transcode#mpp-decode--mpp-encode-fastest

**Describe alternatives you've considered** (optional)
My Host
```
OS: Armbian (24.8.4) aarch64 
Host: Radxa ZERO 3 
Kernel: 6.1.75-vendor-rk35xx 
Uptime: 3 hours, 59 mins 
Packages: 973 (dpkg) 
Shell: bash 5.2.21 
Terminal: /dev/pts/2 
CPU: (4) @ 2.000GHz 
Memory: 2075MiB / 3732MiB
```
Using Casa-OS for dockers. For PiGallery HW accelerated video playback / transcoding get this `yaml`
```
name: xenodochial_mordy
services:
  pigallery2:
    cpu_shares: 90
    command: []
    container_name: pigallery2
    deploy:
      resources:
        limits:
          memory: 3732M
    devices:
      - /dev/dri:/dev/dri
      - /dev/dma_heap:/dev/dma_heap
      - /dev/mpp_service:/dev/mpp_service
      - /dev/rga:/dev/rga
    environment:
      - NODE_ENV=production
    hostname: pigallery2
    image: bpatrik/pigallery2:latest
    labels:
      icon: https://bpatrik.github.io/pigallery2/assets/icon_inv.png
    ports:
      - target: 80
        published: "3000" #use your port
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /DATA/AppData/pigallery2/config
        target: /app/data/config
      - type: bind
        source: /media/nas_2/img_gallery #use your location
        target: /app/data/images
      - type: bind
        source: /media/nas_2/tmp #use your location
        target: /app/data/tmp
      - type: bind
        source: /usr/bin/ffmpeg
        target: /bin/ffmpeg
      - type: bind
        source: /usr/bin/ffprobe
        target: /bin/ffprobe
      - type: bind
        source: /usr/bin/ffplay
        target: /bin/ffplay
    cap_add: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://bpatrik.github.io/pigallery2/assets/icon_inv.png
  index: /
  is_uncontrolled: false
  port_map: "3000"
  scheme: http
  store_app_id: xenodochial_mordy
  title:
    custom: pigallery2
    en_us: pigallery2
```

I also edited `/app/data/config/config.json` & changed `"mp4Codec": "libx264",`  - > `"mp4Codec": "h264_rkmpp", ` but failed. 
I also applied `video.js` patches as mentioned https://github.com/bpatrik/pigallery2/issues/592 but codec discovery kept on failing even though HW `/dev` devices are made available to docker

Without any custom arguments like `-hwaccel rkmpp` & using default codec `libx264` ...video conversion works properly indicating proper `ffmpeg` <> `container` communication & I can see `ffmpeg` full syntax in `htop`

Most likely console error states that it cannot find `*_rkmpp` codec or input params like `-hwaccel rkmpp` are unavailable this code portion is culprit

> https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#querying-ffmpeg-capabilities
